# default values
all:
# Configurable Variables
  pager:
    min: 10
    max: 40
    step: 10
    friendpage: 10
  web:
    name: itbhuglobal.org 
  mail:
    server_type: smtp
    hostname:    localhost
    username:    
    password:    
    character:   utf-8
  from: 
    mail: admin@itbhuglobal.org
    name: ITBHUGlobal.org Administrator
  to:
    adminmail: admin@itbhuglobal.org
  names:
    org: ITBHU Global
  urls:
    claim: http://version2-test.itbhuglobal.org/
  privacyicon:
    1: prvme.gif
    2: prvfriends.gif
    3: prvbhu.gif
    4: globe.png
  privacytitle:
    1: Visible To - None
    2: Visible To - Friends
    3: Visible To - IT BHU
    4: Visible To - All
  year:
    start: 1923
    end:   2013
  privacy:
    message: Pvt
  profile:
    dummyimage: /uploads/profilepic/userDummy.jpg
    blankSection: No data to show in this section
  rolename:
    admin: Administrators
    auth: Authorizers
    masterauth: Master Authorizers
  headerrepeat:
    after: 15
  lortext:
    location: Current Location
    employer: Current Employer
    position: Current Position
    linkedin: LinkedIn
    general: Wall
    email: Email
    badge: Badge
  salt:
    password: I am Indian.
# 1: me, 2: friends, 3: ITBHU, 4: Everyone 
  defaultprivacy:
    roll: 4
    enrol: 1
    year: 4
    branch: 4
    degree: 4
# Anything below this line Must NOT be changed
  lor:
    location: 1
    employer: 2
    position: 3
    linkedin: 4
    general: 5
    email: 6
    badge: 7
  islocked:
    approved: 0
    unclaimed: 1
    claimed: 2
    newreg: 3
    invalid: 5
  role:
    superadmin: 1
    admin:      2
    masterauth: 3
    auth:       4
    user:       5
    guest:      6
  authcode:
    none:       0
    classauth:  1
    otherauth:  2
    masterauth: 3
  privacycode:
    me:         1
    friends:    2
    org:        3
    world:      4
  friend:
    req: 1
    app: 2
    rej: 3
  address:
    0: Home
    1: Work
    2: Permanent
  usertype:
    0: Student
    1: Alumni
    2: Faculty
  usertypecode:
    Student: 0
    Alumni: 1
    Faculty: 2
